language: ruby
script: ./script/cibuild
before_install:
  - ./script/bootstrap
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  allow_failures:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: false
  slack:
    secure: pms4y+KAAznnss/WF3cl7Nsm9gTNe4gTGQYjqcCC7Ygd9Ecuh1W76g2ttwdk4dXQMJE0+2M7TiEPSQijA/zdvjiaFsjm7ghLmyAJze1Yon9RL/JScF+2Ryqun/5LMMAN7vlEJ2FtYkBwCb9BpJNhmwSz5QH110nFvOo3cwgl+1cfFJyxtIT1ByEedrdRg7hfaETiHal7OG0MQcvJcQAh/xxjCEYq9ljRbWCDOYDWPnrmq4abqvZfZaXKg6xj5ZZIXQVWSbguCoao1zvWrxPAF5r2jJWlbL3AcAPRl2CdjmKWzubrf2xV0mwEGx+LbRwZB0ePw3jCg0+u+3QHtd2Dxs/25llk6zKB4KnfKDtlPSuBixFiQLXs2HowJN+0n0gLfbnSqCxsBeToDu7+tVkeMNa5CK6PMes8B2n2C1b7w4Q4bugf9BFFUMPZ2QXx738Bs6zXtI0nB42HV8fCIqtBfVtkdI7OeJRGj3JCvNajocz2gj5XdyW40alkcdPq7rqSqJecE6PfUIJIzDYlOmdcPbZlQjLhq1EWHPviycyIq4/Ddjj3oO747C97HsvoH7MwbCj+/A3hkP0sTJBcDUyCtMLIi54q1fZVKuWKU3jA92kWb06X0FPHBUH8PUF+0gw85sANcBRFTlLEMI7VDq/L8ahWMYCdx/J7+HWkClx6JJw=
